- src/styles/ontimize-theme-styles-flat.scss
- Updated styles for disabled buttons
- Set primary color to accept button in dialogs
> Updated dialog styles

- package.json
- src/styles/flat/variables.scss
- src/styles/ontimize-theme-styles-flat.scss
- Updated flat styles
- Added the ability to configure status colors(primary, success, danger,warning, info,..)
> [8.x.x] Updated flat style

- package.json
- src/styles/ontimize-theme-styles-flat.scss
- Added .o-button-warning class
- Removed shadow and background in actived menu group
> [8.x.x] Improvements in o-app-sidenav

- package-lock.json
- package.json
Fix dependabot security alerts
> Solve vulnerabilities

- .github/workflows/deploy-snapshot-nexus.yml
Added a workflow to publish snapshot versions on Nexus repository
The workflow has to be triggered manually.
> Added workflow for deploying SNAPSHOT versions

- .github/workflows/deploy-snapshot-nexus.yml
- CHANGELOG.md
- gulpfile.js
- implatform-fashion-theme.scss
- package.json
- src/styles/fashion/typography-fashion.scss
- src/styles/fashion/variables.scss
- src/styles/implatform-fashion-theme-styles.scss
- src/styles/lite/typography-lite.scss
- src/styles/lite/typography/ontimize-lite.scss
- src/themes/implatform-fashion-default-theme.scss
> New fashion theme

- CHANGELOG.md
Updated release date in 8.1.0 version
> [8.2.0] CHANGELOG

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/build-ci.yml
- .github/workflows/deploy-snapshot-nexus.yml
- CHANGELOG.md
- gulpfile.js
- implatform-fashion-theme.scss
- package-lock.json
- package.json
- src/styles/fashion/typography-fashion.scss
- src/styles/fashion/variables.scss
- src/styles/implatform-fashion-theme-styles.scss
- src/styles/lite/typography-lite.scss
- src/styles/lite/typography/ontimize-lite.scss
- src/themes/implatform-fashion-default-theme.scss
> Version 8.2.0

- src/styles/fashion/variables.scss
- src/styles/implatform-fashion-theme-styles.scss
- src/styles/lite/form-field/o-form-field-outline-theme.scss
-  Remove layout padding
-  Fixed hover styles in the buttons with class mat-accent
- Set border in mat-icon-button buttons of the o-list, o-table, o-grid and o-form
- Fixing bug in input placeholder overlapping
> [8.x.x] Changes fashion theme

- CHANGELOG.md
- package-lock.json
- package.json
Updated CHANGELOG.md
Updated version in package.json
> [8.x.x] Updated version

- CHANGELOG.md
- package.json
First commit for 8.3.0 version
> [8.x.x] First commit for 8.3.0 version

- CHANGELOG.md
- src/styles/fashion/typography-fashion.scss
- src/styles/implatform-fashion-theme-styles.scss
- src/styles/lite/typography-lite.scss
- src/styles/ontimize-theme-styles.scss
Resolving breaking changes of ontimize-web-ngx related to issue [#1044](https://github.com/OntimizeWeb/ontimize-web-ngx/issues/1044)
> Resolving breaking changes of issue #1044

- .github/workflows/build-ci.yml
- .github/workflows/build-release.yml
- .github/workflows/deploy-snapshot-nexus.yml
- .github/workflows/release-preview.yml
> Fixed NodeJS 12 warning on actions

- CHANGELOG.md
- package-lock.json
- package.json
- Updated CHANGELOG
- Update version to 8.4.1
> Update info for hotfix 8.4.1

- .github/workflows/build-manually.yml
- .github/workflows/build-release.yml
- .github/workflows/prepare-release.yml
> Update workflows involved into release process

- src/styles/implatform-fashion-theme-styles.scss
> Fixed incorrect background being set in tab content.

- src/styles/implatform-fashion-theme-styles.scss
1. Differentiate the accept and cancel buttons in modal popup
2. Delete common css with ontimize-web-ngx
> FASHION STYLE: Differentiate the accept and cancel buttons in modal popup

- src/styles/lite/form-field/o-form-field-theme.scss
- src/styles/lite/typography/ontimize-lite.scss
> Set line-height to 1.125

- package-lock.json
- package.json
Automated pull request for synchronizing released version (8.5.0) into develop branch
> Sync release 8.5.0 to develop

- package-lock.json
- package.json
Set version and update dependencies
> Migration 9.x.x
